name: Build & Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install libzip
      run: sudo apt-get install -y libzip-dev
    - uses: actions/checkout@v4
    - name: make
      run: make HAVE_LIBZIP=1
    - name: make tests
      run: make HAVE_LIBZIP=1 tests
  msys2-mingw64:
    # https://www.msys2.org/docs/ci/
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git make mingw64/mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-libzip
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          make HAVE_LIBZIP=1 HAVE_GZIP=1 clean tests
