name: Linux Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install libzip
      run: sudo apt-get install -y libzip-dev
    - uses: actions/checkout@v4
    - name: make
      run: make HAVE_LIBZIP=1 HAVE_GZIP=1
    - name: make tests
      run: make HAVE_LIBZIP=1 HAVE_GZIP=1 tests
